### ISSUE TITLE
Fix CSS in default template and error templates

### ISSUE THREAD

**Issue by kuboslav** [bcit-ci/CodeIgniter#295]
First error is wrong wendor prefix in pseudo-element selection:

``` css
::selection{ background-color: #E13300; color: white; }
::-moz-selection{ background-color: #E13300; color: white; }
::-webkit-selection{ background-color: #E13300; color: white; }
```

Then add to `#container` **-moz** prefix and non-prefix version of `box-shadow`

``` css
#container {
    box-shadow: 0 0 8px #D0D0D0;
    -moz-box-shadow: 0 0 8px #D0D0D0;
    -webkit-box-shadow: 0 0 8px #D0D0D0;
}
```
